#ifndef __ERROR_H__
#define __ERROR_H__

enum ERROR_BUFFER 
{
    ERROR_BUFFER_EMPTY = -1000,
    ERROR_BUFFER_FULL = -1001,
    ERROR_COPY_DATA_FROM_BUFFER_FAILED = -1002,
    ERROR_COPY_DATA_TO_BUFFER_FAILED = -1003,
    ERROR_BUFFER_STR_READ_FAILED = -1004,
    ERROR_OUTPUT_BUFFER_IS_NULL = -1005,
    ERROR_OUT_OF_RANGE = -1006,
};

enum ERROR_NETPACKET 
{
    ERROR_PARSE_NETPACKET = -1050,
    ERROR_NETPACKET_BUF_IS_FULL = -1051,
}

#endif