#ifndef __SERVER_DEFINE_H__
#define __SERVER_DEFINE_H__

enum EVENT_HANDLER {
    TYPE_LISTEN_FD = 1000,
    TYPE_NETWORK_FD = 1001,
    TYPE_PIPE_FD = 1002,
    TYPE_FILE_FD = 1003,
};

enum NETPACKET {
    NETPACKET_INCOMPLETE = 1050,
    NETPACKET_COMPLETE = 1051,
    // 包处理状态
    NETPACKET_HANDLE_IDLE = 1052, // 空闲
    NETPACKET_HANDLE_MSG = 1053, // 正在处理消息
};

enum TCP_MANAGER {
    TCP_MANAGER_REACTOR_REGISTER = 1100,
    TCP_MANAGER_REACTOR_LOGOUT = 1101,
    TCP_MANAGER_RECV_DATA = 1102,
    TCP_MANAGER_SOCK_FD = 1103,
    TCP_MANAGER_INNER_MSG = 1104,
};

////////////////////// inner_msg_id /////////////////////////

enum REACTOR_MSG_ID {
    REACTOR_ADD_FD = 1150,
    REACTOR_DEL_FD = 1151,
};

enum MSG_HANDER_MSG_ID {
    MSG_DATA_BUFFER = 11500,
};

#endif